/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AdvertisingCreateNestedManyWithoutProductsInput } from "./AdvertisingCreateNestedManyWithoutProductsInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { InventoryCreateNestedManyWithoutProductsInput } from "./InventoryCreateNestedManyWithoutProductsInput";
import { PricingCreateNestedManyWithoutProductsInput } from "./PricingCreateNestedManyWithoutProductsInput";

@InputType()
class ProductCreateInput {
  @ApiProperty({
    required: false,
    type: () => AdvertisingCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => AdvertisingCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => AdvertisingCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  advertisings?: AdvertisingCreateNestedManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  category?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  imageUrl?: string | null;

  @ApiProperty({
    required: false,
    type: () => InventoryCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => InventoryCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => InventoryCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  inventories?: InventoryCreateNestedManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => PricingCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => PricingCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => PricingCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  pricings?: PricingCreateNestedManyWithoutProductsInput;
}

export { ProductCreateInput as ProductCreateInput };
